"""Add token_usage to agent_runs

Revision ID: 0b51d18d8c5a
Revises: f28c02bc5be1
Create Date: 2026-07-18 16:21:48.310807

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0b51d18d8c5a'
down_revision: Union[str, Sequence[str], None] = 'f28c02bc5be1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_runs', sa.Column('token_usage', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_runs', 'token_usage')
    # ### end Alembic commands ###
